### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by drasko** [frankh/nano#6]
Great work here, guys!

I was thinking of Nano rewrite in Go, so I gave google a search - led me to here.

I will explore a bit more project in the following days, but can you please:
- Enable the issues on the Consenbus `core` repo: https://github.com/consenbus/core
- Enable the Slack community channel missing on the Consenbus main page: http://consenbus.org/

**Comment by seqs** [comment]
@drasko 

Thanks for your suggestion, we have been enabled the issues on the consenbus `core` repo and also open the slack community channel.

We are at an early development stage, whether you have questions, comments or suggestions we are always glad to hear from you.

**Comment by drasko** [comment]
@seqs I am interested to help. Looking for some tech documents, but I guess we can take this on Slack.

Will you be opening the Slack to public? Currently it looks invitation-only based.

**Comment by seqs** [comment]
@drasko You can find us on Gitter: https://gitter.im/consenbus/core , we have some access problems with Slack.
